######################################################################
# Automatically generated by qmake (2.01a) Wed May 9 17:47:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h options.h
FORMS += mainwindow.ui options.ui
SOURCES += main.cpp mainwindow.cpp options.cpp
